In [2]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path.cwd().parent / "data" / "raw"

csv_files = list(DATA_PATH.glob("*.csv"))

print("CSV files found:")
for file in csv_files:
    print(file.name)

print("\nTotal CSV files:", len(csv_files))

CSV files found:

Total CSV files: 0

In [4]:
for file in csv_files:

    df = pd.read_csv(file)

    print("\n" + "=" * 70)
    print(f"FILE: {file.name}")
    print("=" * 70)

    print(f"Rows      : {df.shape[0]}")
    print(f"Columns   : {df.shape[1]}")

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nFirst 5 Rows:")
    display(df.head())

In [5]:
for file in DATA_PATH.iterdir():
    print(file.name, file.is_file(), file.suffix)

customers False
orders False
order_items False
payments False
products False

In [6]:
from pathlib import Path

DATA_PATH = Path.cwd().parent / "data" / "raw"

for folder in DATA_PATH.iterdir():
    if folder.is_dir():
        print(f"\n📁 {folder.name}/")

        for file in folder.iterdir():
            print(f"   └── {file.name}")

📁 customers/
   └── Customers.csv

📁 orders/
   └── Orders.csv

📁 order_items/
   └── Order_items.csv

📁 payments/
   └── Payments.csv

📁 products/
   └── Products.csv

In [7]:
csv_files = list(DATA_PATH.rglob("*.csv"))

print("CSV files found:", len(csv_files))

for file in csv_files:
    print(file)

CSV files found: 5
e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\customers\Customers.csv
e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\orders\Orders.csv
e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\order_items\Order_items.csv
e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\payments\Payments.csv
e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\products\Products.csv

In [8]:
import pandas as pd

for file in csv_files:

    df = pd.read_csv(file)

    print("\n" + "=" * 80)
    print(f"FILE: {file}")
    print("=" * 80)

    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:", df.duplicated().sum())

    print("\nFirst 5 Rows:")
    display(df.head())

================================================================================
FILE: e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\customers\Customers.csv
================================================================================
Rows: 89316
Columns: 4

Column Names:
['customer_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Data Types:
customer_id                 object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

Missing Values:
customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Rows: 0

First 5 Rows:

    customer_id  customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                     58125     varzea paulista             SP
1  PxA7fv9spyhx                      3112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                      4119             jandira             SP
3  EOEsCQ6QlpIg                     18212          uberlandia             MG
4  mVz5LO2Vd6cL                     88868            ilhabela             SP

================================================================================
FILE: e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\orders\Orders.csv
================================================================================
Rows: 89316
Columns: 7

Column Names:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_timestamp', 'order_estimated_delivery_date']

Data Types:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_timestamp        object
order_estimated_delivery_date    object
dtype: object

Missing Values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
dtype: int64

Duplicate Rows: 0

First 5 Rows:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18

================================================================================
FILE: e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\order_items\Order_items.csv
================================================================================
Rows: 89316
Columns: 5

Column Names:
['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges']

Data Types:
order_id             object
product_id           object
seller_id            object
price               float64
shipping_charges    float64
dtype: object

Missing Values:
order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

Duplicate Rows: 0

First 5 Rows:

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66

================================================================================
FILE: e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\payments\Payments.csv
================================================================================
Rows: 89316
Columns: 5

Column Names:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Data Types:
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

Missing Values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Duplicate Rows: 0

First 5 Rows:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15

================================================================================
FILE: e:\Data Engineering\ecommerce-data-engineering-pipeline\data\raw\products\Products.csv
================================================================================
Rows: 89316
Columns: 6

Column Names:
['product_id', 'product_category_name', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Data Types:
product_id                object
product_category_name     object
product_weight_g         float64
product_length_cm        float64
product_height_cm        float64
product_width_cm         float64
dtype: object

Missing Values:
product_id                 0
product_category_name    308
product_weight_g          15
product_length_cm         15
product_height_cm         15
product_width_cm          15
dtype: int64

Duplicate Rows: 61865

First 5 Rows:

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0
4,1lycYGcsic2F,toys,300.0,17.0,4.0,12.0